### ISSUE TITLE
Keep display static 

### ISSUE THREAD

**Issue by weiweihuanghuang** [Mark2Mark/Show-Distance-And-Angle-Of-Nodes#2]
I made a fork that keeps display static, I think it's much better now as it doesn't get in the way of my drawing. Just letting you know in case you'd like to implement

https://github.com/weiweihuanghuang/Show-Distance-And-Angle-Of-Nodes/tree/patch-1

**Comment by DeutschMark** [comment]
Thanks for the input. It is also an interesting solution. Nevertheless I would like to refuse to merge. This is due to two things: a) I myself want it to be right at spot of sight (which indeed would be in the way sometimes). This is definitely a matter of taste. And b) I reserved the corners and sides of the view for other plugins. Some of them are going to be released soon and they definitely need to be positioned out of the way :)

I appreciate your ideas anyway! Thanks for this. Btw: the icons you currently use might be confusing for new users, since the arrow indicates a vertical distance. Maybe there is some more apprpriate symbol. Just my 2 cents.

**Comment by weiweihuanghuang** [comment]
Looking forward to seeing them!
Yeah I realised, there wasn't any other more legible distance symbol.

**Comment by DeutschMark** [comment]
Perhaps you could draw your own. Check https://github.com/simoncozens/GlyphsPlugins/releases/ for how to implement these. Otherwise, it is still good anyway. No big deal at all.
