### ISSUE TITLE
Some Feature Requests

### ISSUE THREAD

**Issue by Nevu** [Mark2Mark/Show-Distance-And-Angle-Of-Nodes#3]
Hi,

first: I love this plugin so much, one of the best this month.

I have some smaller feature requests which could improve this plugin.

a) Maybe it its a better visualization not to set the showing values in the blue layer but just as they are.
Especially while measuring smaller distances. Please see img1.

![deck_one](https://cloud.githubusercontent.com/assets/2456068/11418859/0508e05e-9424-11e5-99cb-0191084a08a4.png)

b) Could be nice if the plugin ignores reference points between the measurement. 

Let me explain: there is a distance in order point a, point b and point c; and it will measure just the max distance from point a to point c. For now nothing happened. But could be usefull to ignore all points within the distance (point b) and get the max-distance (ponit a to point c).

I would like it for the case, when handles and notes are at the same point. Please see img2, the jawbone of the e, here are handles and nodes in the same position ...

This mechanic could also be usefull to measure the length of a handel-bar (with a note between, for sure)

![deck_two](https://cloud.githubusercontent.com/assets/2456068/11418964/b3bf9f2a-9424-11e5-8ebd-2dba6e6cb843.png)

thanks
and
respect for that work

**Comment by DeutschMark** [comment]
Hi @Nevu,

Many thanks for your input. I really appreciate this. I am definitely willing to consider your thoughts, but please let me ask some things:
1)
I tried to position the label exactly in between the two selected elements, because this is the most neutral position no matter where in the drawing your selection is made, plus it is still right at spot of sight, where I preferred it over the grey info box at the bottom of the screen. When I had it put it to for instance the left side and without background, I could often not read the numbers because they interfered with the path. Perhaps putting it to the side but keeping the background could be an improvement. I’ll try.
2)
You are right, the plugin is triggered only when exactly two elements are selected. This is mainly due to the math behind it and that there is no way to get the order of selection other than the order of points of the bezier path itself. But i got an idea that I will try out.
For the meantime I’d suggest to not have Offcurve points exactly on Incurve points anyway. It is not forbidden, but no good drawing habit (see e.g. https://forum.glyphsapp.com/t/adding-a-handle/2019 ). If you still want to keep it, you could make your selection by clicking on two nodes instead of drawing the selection-rectangle around them.

Thanks again four your feedback. I’ll give it a try …

**Comment by DeutschMark** [comment]
Well, I could manage to offset the Label a bit. It works especially in cases when the path is rather straight. The idea I had about your second issue – ignoring point B from A-B-C – did not work out. Sorry for that.
